#!/bin/bash
FILE="lib/data/products-ultimate.json"
cp "$FILE" "${FILE}.bak"
sed -i '' 's/chainette/chaînette/g' "$FILE"
sed -i '' 's/Chainette/Chaînette/g' "$FILE"
sed -i '' 's/BRACELET chaînette DORÉE/Bracelet chaînette doré/g' "$FILE"
sed -i '' 's/COLLIER PIERRES/Collier pierres/g' "$FILE"
sed -i '' 's/CHAINE DE CHEVILLES ARGENTÉE/Chaîne de cheville argentée/g' "$FILE"
sed -i '' 's/PORTE-CLÉ NÉPALAIS/Porte-clé népalais/g' "$FILE"
sed -i '' 's/pierre de JADE/pierre de jade/g' "$FILE"
sed -i '' 's/Pierre de lune/pierre de lune/g' "$FILE"
sed -i '' 's/aqua-marine/aigue-marine/g' "$FILE"
sed -i '' 's/fermoire/fermoir/g' "$FILE"
sed -i '' 's/ponpon/pompon/g' "$FILE"
sed -i '' 's/PONPON/pompon/g' "$FILE"
echo "✅ Corrections appliquées"
